dependencies {
	api project(':framework-starter:framework-security-starter:framework-security-common')
	// security
	implementation "cn.dev33:sa-token-spring-boot-starter:${saTokenVersion}"
	// test
	testImplementation project(':framework-test')
	testImplementation project(":framework-web")
	testImplementation project(":framework-system")
}
