spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %p %X{X-Request-Id} %c{1}[%line]: %m%n'

springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
