server:
  port: 8090

spring:
  profiles:
    include: common

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 123456

  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate: trace
