# gradle
org.gradle.caching=false
#org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
# ignore no source project
ignoreNoSourceProject=framework-starter,framework-security-starter,app-web-business
# biz source project
bizProjectPrefix=app
# application
kotlinVersion=1.9.23
springBootVersion=3.2.4
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
kotlinVersion=1.9.24
# https://github.com/graalvm/native-build-tools
nativeBuildToolsVersion=0.9.27
