# gradle
org.gradle.caching=false
#org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
# ignore no source project
ignoreNoSourceProject=framework-starter,framework-security-starter,app-web-business
# biz source project
bizProjectPrefix=app
# application
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib
kotlinVersion=2.0.20
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
springBootVersion=3.4.0
# https://github.com/graalvm/native-build-tools
nativeBuildToolsVersion=0.10.2
