dependencies {
	api project(':framework-fsm-core')
	api project(':framework-web')

	api 'org.springframework.boot:spring-boot-starter-web'
	api "com.baomidou:mybatis-plus-spring-boot3-starter:${mybatisPlusVersion}"

	// test
	testImplementation project(':framework-test')
	testImplementation "org.openjdk.jmh:jmh-core:${jmhVersion}"
	testImplementation "org.openjdk.jmh:jmh-generator-annprocess:${jmhVersion}"
}
