dependencies {
	api project(':framework-common')
	api 'org.springframework.boot:spring-boot-starter-web'
	api "com.baomidou:mybatis-plus-spring-boot3-starter"
	implementation "com.baomidou:mybatis-plus-jsqlparser"
    implementation 'org.springframework.boot:spring-boot-configuration-processor'
	// observability, etc
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
//	implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
	// docs
	api "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

	// test
	testImplementation project(':framework-test')
}
