name: "Validate Gradle Wrapper"
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:

  validation:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    name: "Validation gradle wrapper"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
